headers:
  X-SERVICE-VIC-SAML:
    description: "SAML E2E token retrieved from the consumer"
    required: false
  X-SERVICE-VIC-E2E-Trust-Token:
    description: "E2E Trust token retrieved from the consumer"
    required: false